### PR TITLE
Version 1.4 (OTP 19.2, Node 6.9.4)

### PR DESCRIPTION
**Pull request by maennchen**
Implementation of openshift-s2i/s2i-phoenix#7

### CODE REVIEW

**Comment by maennchen** [comment]
ping @jawnsy

**Comment by jawnsy** [comment]
Sorry, don't know why I didn't see this, thanks for the reminder! Will try to take a look soon (please continue to nag me as needed)

**Comment by maennchen** [comment]
Ping @jawnsy

**Comment by maennchen** [comment]
Ping @jawnsy again.

Is someone managing this repo? It would be nice to actually release this before 1.4 is deprecated again.

**Comment by maennchen** [comment]
It doesn't seem that anyone is actually interested in this. Closing therefore.

**Pull request closed without merging**
